/*
github.com/radu-matei/event-operator
*/
// This file was automatically generated by lister-gen

package v1alpha1

// EventProviderListerExpansion allows custom methods to be added to
// EventProviderLister.
type EventProviderListerExpansion interface{}

// EventProviderNamespaceListerExpansion allows custom methods to be added to
// EventProviderNamespaceLister.
type EventProviderNamespaceListerExpansion interface{}
