apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventproviders.eventprovider.radu-matei.com
spec:
  group: eventprovider.radu-matei.com
  version: v1alpha1
  names:
    kind: EventProvider
    plural: eventproviders
  scope: Namespaced
