apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventproviders.eventprovider.k8s.io
spec:
  group: eventprovider.k8s.io
  version: v1alpha1
  names:
    kind: EventProvider
    plural: eventproviders
  scope: Namespaced
