required = ["k8s.io/code-generator/cmd/client-gen"]

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-6.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.9"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.9"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.9"


# this is the commit that k8s.io/code-generator uses 
# as dependency for k8s/io/gengo
[[override]]
  name = "k8s.io/gengo"
  revision = "b58fc7edb82e0c6ffc9b8aef61813c7261b785d4"