version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/radu-matei/events-operator
    steps:
      - checkout

      - run: make dep
      - run: make build
