/*
github.com/radu-matei/event-operator
*/
// This file was automatically generated by informer-gen

package v1alpha1

import (
	eventprovider_v1alpha1 "github.com/radu-matei/events-operator/pkg/apis/eventprovider/v1alpha1"
	versioned "github.com/radu-matei/events-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/radu-matei/events-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/radu-matei/events-operator/pkg/client/listers/eventprovider/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// EventProviderInformer provides access to a shared informer and lister for
// EventProviders.
type EventProviderInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.EventProviderLister
}

type eventProviderInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEventProviderInformer constructs a new informer for EventProvider type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEventProviderInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEventProviderInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEventProviderInformer constructs a new informer for EventProvider type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEventProviderInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EventproviderV1alpha1().EventProviders(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EventproviderV1alpha1().EventProviders(namespace).Watch(options)
			},
		},
		&eventprovider_v1alpha1.EventProvider{},
		resyncPeriod,
		indexers,
	)
}

func (f *eventProviderInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEventProviderInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *eventProviderInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&eventprovider_v1alpha1.EventProvider{}, f.defaultInformer)
}

func (f *eventProviderInformer) Lister() v1alpha1.EventProviderLister {
	return v1alpha1.NewEventProviderLister(f.Informer().GetIndexer())
}
